version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/demo-dir
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install'
      - run:
          name: install grunt module
          command: 'sudo npm install -g grunt-cli'    
      - run:
          name: create directory
          command: mkdir -p ~/demo-dir/{testresult,codecoverage}
      - run:
          name: code-coverage
          command: './node_modules/.bin/istanbul report cobertura --dir  shippable/codecoverage/'
